---
title: "Analysis for Large-scale clustering of longitudinal faecal calprotectin and CRP profiles in inflammatory bowel disease: Findings from the Lothian IBD Registry"
format:
  html:
    code-tools: false
date: ""
sidebar: false
date-format: ""
title-block-banner: false # can set as hex 
author:
  - name: "Nathan Contantine-Cooke" 
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    corresponding: true
    affiliations:
      - ref: CGEM
      - ref: HGU
  - name: "Charlie W. Lees"
    url: https://scholar.google.com/citations?user=rHc0qf0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: CGEM
      - ref: IBD
  - name: "Catalina A. Vallejos"
    url: https://scholar.google.com/citations?user=lkdrwm0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: HGU
      - ref: Turing
---

```{R}
#| echo: false
x <- 1 # If there's no code block then inline R code below won't work. 
```

## About

This website presents the analyses carried out for
*Large-scale clustering of longitudinal faecal calprotectin and C-reactive protein profiles in inflammatory bowel disease*
by Constantine-Cooke et al. In this work, we expand upon our previous research
which clustered faecal calprotectin (FC) profiles for a subset of Crohn's
disease patients [@constantine-cooke2023] by clustering FC and C-reactive
protein (CRP) profiles across Crohn's disease, ulcerative colitis, and
inflammatory bowel disease unclassified patients treated by the
[NHS Lothian health board](https://www.nhslothian.scot/). 

The analysis pipeline for this project can be categorised into three stages:

1. _Before model fitting_, where data obtained from clinicians are
   reformatted and any data quality issues are dealt with. Additionally, 
   baseline data (i.e data available at diagnosis) were explored via descriptive
   analyses.
2. _Model fitting_, where latent class mixed models are fitted with differing
   numbers of assumed clusters and the most appropriate models are chosen for
   FC and CRP. 
3. _After model fitting_, where post hoc associations between baseline data and
   cluster membership are explored. The relationship between FC and CRP
   clustering is also analysed. 
   
## Using this website

The navigation menu at the top of the page will allow you to navigate through
the steps of the analysis pipeline.  The code button at the top of each page can
be used to show all code blocks instead of clicking on the code buttons for each
individual block of code. Moving the mouse pointer over any citations will
produce a pop up box with reference details. Clicking on the citation will link
to the bibliography at the bottom of the page. 

## Software

All analyses have been generated using
[`r strsplit(R.version$version.string, " (", fixed = TRUE)[[1]][1]`](https://www.r-project.org).

Please see the *Session Information* sections at the end of each page for the
R packages and the respective versions used. 

This website has been generated using the [Quarto](https://quarto.org)
scientific publishing system built on top of [pandoc](https://pandoc.org). A
list of major components used by Quarto can be found
[here](https://quarto.org/license.html)
